Feature/NR-36 add trending games
lukatarman/steam-game-stats-backend pull request #120
Opened 2023-06-04 13:34 UTC by lukatarman

Related issue: #3

2023-06-07 07:07 UTC, stas-at-ibm requested changes
Great job as always. Minor things only.

2023-06-07 07:07 UTC, stas-at-ibm commented on src/infrastructure/repositories/games.repository.js
> +      this.#addAveragePlayersAtCustomDayProperty(timePeriodInMs),
`addAveragePlayersAtCustomDayProperty > addAveragePlayersInTimePeriodProperty`

2023-06-07 07:07 UTC, stas-at-ibm commented on src/infrastructure/repositories/games.repository.js
> +      { $unset: "averagePlayersAtCustomDay" },
rename like above

2023-06-07 07:07 UTC, stas-at-ibm commented on src/infrastructure/repositories/games.repository.js
> +  #addAveragePlayersTodayProperty = () => {
ok I get everything except those two big functions :), addAveragePlayersTodayProperty, addAveragePlayersAtCustomDayProperty...to many syntax which I don't know, but I can ask gpt to explain actually

2023-06-11 06:15 UTC, lukatarman commented on src/utils/time.utils.spec.js
> +    describe("passing a value of 12 into the function", () => {
Yeah I've been trying to do this more lately. Let me know how it is in the other PR

2023-06-11 06:15 UTC, lukatarman commented on src/utils/time.utils.spec.js
> +  describe(".daysToMs", () => {
:)

2023-06-11 16:51 UTC, stas-at-ibm approved these changes
Just one remark. You can merge after.

2023-06-11 16:51 UTC, stas-at-ibm commented on src/features/game-queries/game.queries.controller.js
> +  async getTrendingGames(timePeriodInMs, returnAmount, minimumPlayers) {
remove here also, only leave in repo othewise you pass in undefined

2023-06-12 12:47 UTC, merged