Feature/NR-46 Add update missing properties calls to repo
lukatarman/steam-game-stats-backend pull request #144
Opened 2023-07-28 09:20 UTC by lukatarman

Related issue: #143

2023-07-28 10:06 UTC, stas-at-ibm requested changes
🥇 a medal for the small PR! You are a quick learner :)

2023-07-28 10:06 UTC, stas-at-ibm commented on src/models/game.mocks.js
> +export const getSixGamesWithMissingProperties = () => {
getSixGamesWithPartlyMissingDetails

2023-07-31 13:14 UTC, stas-at-ibm requested changes
see comments below!

2023-07-31 13:14 UTC, stas-at-ibm commented on backend/src/infrastructure/database/repositories/games.repository.spec.js
> +    describe("When the database contains 6 matching games", function () {
remove

2023-07-31 13:14 UTC, stas-at-ibm commented on backend/src/infrastructure/database/repositories/games.repository.spec.js
> +        this.games = [
extract

2023-07-31 13:14 UTC, stas-at-ibm commented on backend/src/infrastructure/database/repositories/games.repository.spec.js
> +          this.games.map(async (game) => gamesRepo.getOneGameById(game.id)),
remove async

2023-07-31 15:32 UTC, lukatarman commented on backend/src/infrastructure/database/repositories/games.repository.spec.js
> +        expect(this.result[0].id).toBe(239140);
I left the id's if we ever need to change/check something - it will be much easier to see which game is being found.

2023-07-31 16:13 UTC, stas-at-ibm approved these changes
Great job! I merge!

2023-07-31 16:13 UTC, stas-at-ibm commented on backend/src/infrastructure/database/repositories/games.repository.spec.js
> +      it("the game is an instance of Game", function () {
🏅

2023-07-31 16:13 UTC, merged